version: "3.9"
services:
    db:
        container_name: kanban-board-db
        image: postgres:15-alpine
        environment:
          - POSTGRES_DB=${DB_NAME}
          - POSTGRES_USER=${DB_USER}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
          - ${DB_PORT}:5432
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
          - db
    api:
        container_name: kanban-board-api
        build:
          context: ${API_PATH}
          dockerfile: Dockerfile.dev
        environment:
          - PORT=${API_INTERNAL_PORT}
          - HASURA_PORT=${HASURA_PORT}
          - DB_HOST=${DB_HOST}
          - DB_PORT=${DB_PORT}
          - DB_NAME=${DB_NAME}
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_PASSWORD}
        ports:
          - ${API_PORT}:${API_INTERNAL_PORT}
        volumes:
          - ${API_PATH}:/app
        networks:
          - db
          - hasura
        depends_on:
          - db
          - graphql-engine
    graphql-engine:
        container_name: kanban-board-graphql-engine
        image: hasura/graphql-engine:latest
        ports:
            - ${HASURA_PORT}:8080
        restart: always
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://kanbansuperuser:kanban4ever@db:5432/app
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
            ## uncomment next line to set an admin secret
            HASURA_GRAPHQL_ADMIN_SECRET: adminsecret
        networks:
            - db
            - hasura
        depends_on:
            - db
networks:
    db:
    hasura:

