import { ReactNode } from "react";
import clsx from "clsx";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

// If loading a variable font, you don't need to specify the font weight
const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["400", "500", "700"],
  style: "normal",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={clsx(plusJakartaSans.className)}>
      <body>{children}</body>
    </html>
  );
}
