FROM golang:1.20-alpine

# Add Maintainer Info
LABEL maintainer="Talgat Saribayev <talgat.s@protonmail.com>"

WORKDIR /app

# Install air
RUN go install github.com/cosmtrek/air@latest

# Copy file to workdir
COPY . .

# Install modules
RUN go mod download

EXPOSE 8000
CMD ["air"]
